### ISSUE TITLE
Tasty tests wont work with GHC 7.10.3

### ISSUE THREAD

**Issue by nghamilton** [data61/fp-course#345]

**Comment by gwils** [comment]
To replicate this:

Clone the fp-course
cd fp-course
ghci-7.10.3

```
<interactive>:1:122:
    Not in scope: type constructor or class ‘String’
    Perhaps you meant ‘IsString’ (imported from Course.Core)

<interactive>:1:135:
    Not in scope: type constructor or class ‘String’
    Perhaps you meant ‘IsString’ (imported from Course.Core)

<interactive>:1:121:
    Not in scope: type constructor or class ‘String’
    Perhaps you meant ‘IsString’ (imported from Course.Core)

<interactive>:1:134:
    Not in scope: type constructor or class ‘String’
    Perhaps you meant ‘IsString’ (imported from Course.Core)
```

Recommended action:
Increase the minimum GHC requirement to 8.0.2
GHC 7.10 is four years old, so it's reasonable to expect people to upgrade.
